### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .css_test_script import css_test_script

def create_instance(c_instance):
	return css_test_script(c_instance)